services:
  auth-db:
    image: postgres:16-alpine
    container_name: auth-db
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
    volumes:
      - auth-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  hotel-service:
    build: ./hotel-service
    container_name: hotel-service
    ports:
      - "8082:8082"
    environment:
      HOTEL_API_KEY: HOTEL_SECRET_67890
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8082/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  booking-service:
    build: ./booking-service
    container_name: booking-service
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: postgres
      POSTGRES_URL: jdbc:postgresql://auth-db:5432/booking_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      HOTEL_SERVICE_URL: http://hotel-service:8082
      BOOKING_API_KEY: BOOKING_SECRET_11111
      JWT_SECRET: ubqBq8o9co+y1lA+viUYAnWt1toPVlGGbOdQp/tfisjaacx3dPFM6FjXchLfyWQ8
    depends_on:
      auth-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8083/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/auth_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgrespassword
      API_KEY: AUTH_SECRET_12345
    depends_on:
      auth-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "8084:8084"
    environment:
      SPRING_PROFILES_ACTIVE: h2
      PAYMENT_API_KEY: PAYMENT_SECRET_22222
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8084/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - hotel-service
      - booking-service
      - payment-service

volumes:
  auth-data:
